spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/search_engine
    username: root
    password: kbvjy123
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false


indexing-settings:
  sites:
    #    - url: https://lenta.ru
    #      name: Lenta.ru
    - url: https://playback.ru
      name: PlayBack.Ru
      id: 1
    - url: https://skillbox.ru
      name: Skillbox
      id: 2
    - url: https://lentaerrorurl.ru
      name: LentaError
      id: 3

connection-settings:
  userAgent: Mozilla/5.0 (X11; Fedora;Linux x86; rv:60.0) Gecko/20100101 Firefox/60.0
  referer: https://www.google.com